### ISSUE TITLE
Struggling to get the remote to work on Windows 10

### ISSUE THREAD

**Issue by jung69** [malacalypse/h9-remote#1]
Hi, not sure if this the right way of contacting you but I'd love to get the remote to work on Windows 10. I have tried both via USB and regular midi but the device never shows up as  ''connected" . I can see the H9 in Live and can monitor midi coming in when I move the knob on the H9 but I am having no luck with the remote. Any pointers would be greatly appreciated.
Thank you in advance!

**Comment by malacalypse** [comment]
Hello, I'm sorry for the delay in responding as I've been traveling. 

I don't use nor do I support the Remote on Windows. The remote uses SysEx to talk to the H9 so the standard MIDI used in and through Live won't suffice to connect it. Most likely, you'll need to figure out how to install the required `impmidi` components into your Max externals. I have no idea how to do this on Windows, but perhaps https://www.theimpersonalstereo.com/blog/blog/2016/3/impmidi-cross can help you along with some Max documentation. Once those components are visible in Max, you should be able to connect to your H9 inside the plugin. I'm afraid I can't offer more support than this for Windows, though!

**Comment by jung69** [comment]
Thanks for getting back to me Daniel. I'll give this a go.

All the best,

Jorg
