### ISSUE TITLE
can't use the m4l plugin

### ISSUE THREAD

**Issue by goinz** [malacalypse/h9-remote#7]
On my Windows 10 Ableton live 10.1.9 Setup it doesn't work. I checked all settings several times and no success. If I klick the Rescan Button it jumps away from H9 Pedal to my first midi device and not as wanted to "connected". I tried USB and Midi no way. If I start the max debug it says:
imp.sysexin: Failed to open port '3- MIDISPORT 4x4 In D', port may already be in use by Max. To use disable this input port in Max's MIDI settings.

But I can't find where to disable it. The message appears on all midi devices I choose, doesn't matter which. Please assist I realy want to use the Plugin.

**Comment by malacalypse** [comment]
If you read the documentation, you will note that Windows is not supported and I have no plans to support it. Sorry!
